# Configurações do Spring Boot com o banco de dados PostgreSQL
spring.application.name=eu-te-amo-api
spring.datasource.url=jdbc:postgresql://db.aetyxubofhdcawrhtzri.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Spop11pvp##
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false

# Configurações do servidor
server.port=8081

# Credenciais do Cloudinary
cloudinary.cloud-name=y7axo9l0
cloudinary.api-key=516912266281225
cloudinary.api-secret=--bpnXPZKbshdcN6Th0ntc5tfuo

# Limite de tamanho para upload no Spring Boot
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
