# Configurações do Spring Boot com o banco de dados PostgreSQL
spring.application.name=eu-te-amo-api
spring.datasource.url=jdbc:postgresql://localhost:5432/eu_te_amo
spring.datasource.username=postgres
spring.datasource.password=Spop11pvp#
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

# Configurações do servidor
server.port=8081

# Credenciais do Cloudinary
cloudinary.cloud-name=y7axo9l0
cloudinary.api-key=516912266281225
cloudinary.api-secret=--bpnXPZKbshdcN6Th0ntc5tfuo

# Limite de tamanho para upload no Spring Boot
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
